### ISSUE TITLE
Please update `x11rb` and `core-graphics`

### ISSUE THREAD

**Issue by emilk** [1Password/arboard#128]
…and maybe other dependencies 🙏

**Comment by complexspaces** [comment]
It looks all of the out-of-date dependencies on `main` (https://github.com/1Password/arboard/pull/123 hasn't been released yet) are:
- `windows-sys`: I'm hesitant to update this one until bigger crates like Tokio in the ecosystem adopt it. For the most part everyone else is still on 0.48.
- `core-graphics`: You mentioned this one, and I don't see any blockers to updating it.
- `x11rb`: You mentioned this one as well, and again, no blockers. I like to switch away from `nix` to `rustix`.

Are there any others I missed?

**Comment by Jasha10** [comment]
Recent PR #131 addresses this.
I think this issue can be closed one a new version of `arboard` is released to crates.io

**Comment by complexspaces** [comment]
This is now resolved with [3.3.1](https://github.com/1Password/arboard/releases/tag/v3.3.1) being published. I apologize for the delay on getting these out, but hopefully it wasn't a dealbreaker for you. `arboard` should now be in sync with the rest of the ecosystem.

Once `tokio` bumps their MSRV and the biggest `windows-sys` consumers raise their versions, I'll subsequently bump `arboard`s too.
