### ISSUE TITLE
Is there a memory leak

### ISSUE THREAD

**Issue by morn-0** [1Password/arboard#24]

**Comment by cc-morning** [comment]
It seems that memory is not freed after calling `get_text()` or `get_image()`.

**Comment by cc-morning** [comment]
It seems that other platforms are the same

I `set_image` a picture of about 5 mb size about 8 or 9 times, the whole program about 67mb. then found that the memory area 0x53e32400000-0x53e36000000 is basically the content of this picture data about 60mb. then there are some CLIPBOARD, CLIPBOARD_ MANAGER, ARBOARD_CLIPBOARD strings. I wonder if there is some memory leak or memory not freed in time.
![mem1](https://user-images.githubusercontent.com/90960002/134543568-700b551f-70c7-4626-8789-c73c3c069a43.png)

A comparison of the memory when the program is opened and after the completion of the `set_image` test shows that there is a clear exception in 53e32400000.
![mem2](https://user-images.githubusercontent.com/90960002/134543581-79705b8c-7627-414d-835c-bc922c13c2ca.png)

**Comment by cc-morning** [comment]
The memory dump file is here http://47.100.174.226:8080/s/vmIj

**Comment by ArturKovacs** [comment]
Thanks for reporting this! I think I'll get to this after sorting out #23

**Comment by cc-morning** [comment]
> Thanks for reporting this! I think I'll get to this after sorting out #23

okay

**Comment by cc-morning** [comment]
Hi, any progress so far?

**Comment by mchaliadzinau** [comment]
@morn-0 was you able to find the issue?
I think I've run into this issue but for get_text() as well (have not tried get_image yet...).

**Comment by morn-0** [comment]
> was you able to find the issue?
> I think I've run into this issue but for get_text() as well (have not tried get_image yet...).

Sorry, I haven't had the chance to delve deeper into this issue recently.

**Comment by complexspaces** [comment]
I am going to close this issue since I'm not aware of any more memory leaks in `arboard`. All of the macOS ones have been removed (and tested) in previous releases. Thanks for reporting this before.
