### ISSUE TITLE
The substring array of large images is very large and can be jammed

### ISSUE THREAD

**Issue by Soya-xy** [1Password/arboard#49]
How to avoid getting stuck when the picture is very large, when the bytes is very long, and when using tauri to transmit?

**Comment by ArturKovacs** [comment]
You should run the clipboard operation on a separate thread to keep the UI responsive. You can then send data to the UI thread using a channel or a mutex.

**Comment by complexspaces** [comment]
I'm going to close this issue since its old at this point, and a reasonable answer was provided.

FWIW I have also experienced similar when testing with large images on macOS. The larger it is, the longer it takes to copy out of the system's clipboard memory and into your own process' memory.
