### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by grant0417** [1Password/arboard#72]
Hey, is the maintainer able to make a new release, updating the wl-clipboard-rs  2243d0dca3996fdb9a1f3a96a5a1bfecc2ebd520 removed a dependency on `failure` which is unmaintained and has security issues, see https://rustsec.org/packages/failure.html

**Comment by kjvalencik** [comment]
The next release is in progress. It's current blocked by a proposal to change an API name:

https://github.com/1Password/arboard/pull/70#issuecomment-1204373454

**Comment by grant0417** [comment]
Thanks! Didn't see the pr!
