### ISSUE TITLE
Reading an image from clipboard on wayland prints its bytes to stderr

### ISSUE THREAD

**Issue by kampffrosch94** [1Password/arboard#90]
I believe this line is the culprit
https://github.com/1Password/arboard/blob/c6102b1b8515417bebc000b8c9927fc23b531a36/src/platform/linux/wayland.rs#L139
Probably a simple oversight.

**Comment by complexspaces** [comment]
Thanks for finding these! I've removed both of them, and this cleanup should hopefully be going out soon in the upcoming 3.2 release.
