### ISSUE TITLE
arboard causes crash in WSLg in newer version

### ISSUE THREAD

**Issue by markusdd** [1Password/arboard#94]
This issue is related to https://github.com/emilk/egui/issues/2425 where the problem is documented.

egui 0.20.0 (which I wanted to update from 0.19.0 which works without this problem) does not work in Windows 11 WSLg anymore.

Issue is an error from arboard during startup in the WSLg environment.

This is teh version diff between using egui 0.19.0 and 0.20.0 for arboard from Cargo.lock. So it seems version 3 has this problem while 2 does not.

```diff
 [[package]]
 name = "arboard"
-version = "2.1.1"
+version = "3.2.0"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "dc120354d1b5ec6d7aaf4876b602def75595937b5e15d356eb554ab5177e08bb"
+checksum = "d6041616acea41d67c4a984709ddab1587fd0b10efe5cc563fee954d2f011854"
```

**Comment by complexspaces** [comment]
Hey @markusdd, I apologize for the delay. It has been a busy start to the wee. I see that you closed this but I didn't grasp why from the linked `egui` issue. Did you conclude that the issue isn't coming from `arboard`? Otherwise I can try and look at this.

**Comment by markusdd** [comment]
hi!

right now the situation has evolved a bit and it looks more like the errors are caused by a startup issue in WSLg when egui runs it's winit and clipoard initialization.

We have figured out to get past this and the arboard error is gone so it seems this was caused by something else.

Should this change I will come back and re-open. Thanks!
