### ISSUE TITLE
ArchLinux/Wayland/Sway -- error while interacting with the clipboard: Display parsing error

### ISSUE THREAD

**Issue by eliheuer** [1Password/arboard#98]
I'm trying to run the example in the readme on an ArchLinux/Wayland/Sway desktop environment, but I get the error: `error while interacting with the clipboard: Display parsing error`.

![20230307_02h32m59s_grim](https://user-images.githubusercontent.com/5162664/223308015-5654480d-ddf8-448e-a1c4-1938d99e5534.png)

I see in the readme it says: `There's also an optional wayland data control backend through the wl-clipboard-rs crate. This can be enabled using the wayland-data-control feature.`, but it's not clear how to do that or if it would let me build the example without an error. 

I'm trying to fix a build fail in a GUI application called MFEKglif with this issue.

Thanks!

**Comment by complexspaces** [comment]
Hi there @eliheuer,

I believe the feature flag you're looking for is called [`wayland-data-control`](https://github.com/1Password/arboard/blob/master/Cargo.toml#L15). You can enable it in your project like this:

```toml
[dependencies]
arboard = { version = "3.2", features = ["wayland-data-control"] }
```

Does that solve your problem?

**Comment by pophilpo** [comment]
@complexspaces That did help me getting the text clipboard data from most applications on Wayland, thank you

**Comment by complexspaces** [comment]
No problem, I'm glad that solved things for you. I'm going to close this for now but let me know if you run into any more Wayland-specific problems.
